### ISSUE TITLE
week3 tasks checklist

### ISSUE THREAD

**Issue by zjr-mds** [UBC-MDS/Ranimalsgonewild#11]
function1: @zjr-mds 
- [x] function body 
- [x] unit tests 
- [x] exception handling code

function2: @morganrosenberg50 
- [ ] function body 
- [ ] unit tests 
- [ ] exception handling code

function3: @nrao944 
- [ ] function body 
- [ ] unit tests 
- [ ] exception handling code

function4: @Kylemaj 
- [ ] function body 
- [ ] unit tests 
- [ ] exception handling code

submission: @nrao944 
- [ ] 2 URLs for R packages: link to the repo and link to the releases page

milestone3
- [ ] close the issues by end of the milestone
