### ISSUE TITLE
R package task checklist

### ISSUE THREAD

**Issue by zjr-mds** [UBC-MDS/Ranimalsgonewild#4]
- [x] Create project structure for the R package and push it as a public repository in the UBC-MDS organization on Github.com.

- [x] The name of the repository should be relevant to the package/project topics.

- [x] For now choose the MIT license. You may change it later when you learn more about licenses.

- [x] Use usethis::use_code_of_conduct to add a code of conduct. You may want to customize it further to suit your group.

- [x] Add the team members as authors to the DESCRIPTION file.

- [x] Use usethis::use_tidy_contributing() to add a CONTRIBUTING.md file to your package. 

README.Rmd file. (This can be identical for both projects at this point in the project). In particular, your README.md should contain:

- [x] a summary paragraph that describes the project at a high level

- [x] a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)

- [x] a paragraph describing where your packages fit into the R ecosystem (are there any other R packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).
